window.colorlist_base = 
[
  [
    [[180, 180, 180], [177, 182, 181], [255, 255, 255], [135, 135, 135]],
    [
      ["wool", "0", "White Banner", false, "wool_colored_white", 0],
    ],
    13
  ],
  [
    [[152, 89, 36], [176, 90, 20], [216, 127, 51], [114, 67, 27]],
    [
      ["wool", "1", "Orange Banner", false, "wool_colored_orange", 0],
    ],
    14
  ],
  [
    [[125, 53, 152], [141,55, 134], [178, 76, 216], [94, 40, 114]],
    [
      ["wool", "2", "Magenta Banner", false, "wool_colored_magenta", 0],
    ],
    15
  ],
  [
    [[72, 108, 152], [41, 127, 154], [102, 153, 216], [54, 81, 114]],
    [
      ["wool", "3", "Light Blue Banner", false, "wool_colored_light_blue", 0],
    ],
    16
  ],
  [
    [[161, 161, 36], [180, 152, 42], [229, 229, 51], [121, 121, 27]],
    [
      ["wool", "4", "Yellow Banner", false, "wool_colored_yellow", 0],
    ],
    17
  ],
  [
    [[89, 144, 17], [91, 141, 22], [127, 204, 25], [67, 108, 13]],
    [
      ["wool", "5", "Lime Banner", false, "wool_colored_lime", 0],
    ],
    18
  ],
  [
    [[170, 89, 116], [173, 99, 121], [242, 127, 165], [128, 67, 87]],
    [
      ["wool", "6", "Pink Banner", false, "wool_colored_pink", 0],
    ],
    19
  ],
  [
    [[53, 53, 53], [50, 56, 58], [76, 76, 76], [40, 40, 40]],
    [
      ["wool", "7", "Gray Banner", false, "wool_colored_gray", 0],
    ],
    20
  ],
  [
    [[108, 108, 108], [111, 111, 106], [153, 153, 153], [81, 81, 81]],
    [
      ["wool", "8", "Light Gray Banner", false, "wool_colored_silver", 0],
    ],
    21
  ],
  [
    [[53, 89, 108], [15, 110, 110], [76, 127, 153], [40, 67, 81]],
    [
      ["wool", "9", "Cyan Banner", false, "wool_colored_cyan", 0],
    ],
    22
  ],
  [
    [[89, 44, 125], [97, 35, 130], [127, 63, 178], [67, 33, 94]],
    [
      ["wool", "10", "Purple Banner", false, "wool_colored_purple", 0],
    ],
    23
  ],
  [
    [[36, 53, 125], [42, 48, 120], [51, 76, 178], [27, 40, 94]],
    [
      ["wool", "11", "Blue Banner", false, "wool_colored_blue", 0],
    ],
    24
  ],
  [
    [[72, 53, 36], [92, 60, 35], [102, 76, 51], [54, 40, 27]],
    [
      ["wool", "12", "Brown Banner", false, "wool_colored_brown", 0],
    ],
    25
  ],
  [
    [[72, 89, 36], [66, 88, 16], [102, 127, 51], [54, 67, 27]],
    [
      ["wool", "13", "Green Banner", false, "wool_colored_green", 0],
    ],
    26
  ],
  [
    [[108, 36, 36], [124, 32, 27], [153, 51, 51], [81, 27, 27]],
    [
      ["wool", "14", "Red Banner", false, "wool_colored_red", 0],
    ],
    27
  ],
  [
    [[17, 17, 17], [20, 20, 23], [25, 25, 25], [13, 13, 13]],
    [
      ["wool", "15", "Black Banner", false, "wool_colored_black", 0],
    ],
    28
  ]
]
window.colorlist_patches = {
  "1.13": [
    [[0,0], ['grass_block', '', 'Grass Block', false, 'grass_side', 0]],
    [[0,1], ['slime_block', '', 'Slime Block', true, 'slime', 1]],
    [[1,2], ['birch_log', "'axis':'y'", 'Birch Log (vertical)', false, 'log_birch_top', 2]],
    [[1,3], ['birch_planks', '', 'Birch Planks', false, 'planks_birch', 3]],
    [[1,4], ['birch_slab', '', 'Birch Slab', false, 'slabs_birch', 4]],
    [[1,6], ['end_stone', '', 'End Stone', false, '', 6]],
    [[1,7], ["sandstone_slab", "", "Sandstone Slab", false, "sandstone_slab", 7]],
    [[2,0], ['cobweb', '', 'Cobweb', false, 'web', 0]],
    [[3,1], ['redstone_block', '', 'Block of Redstone', false, '', 1]],
    [[4,1], ['packed_ice', '', 'Packed Ice', false, 'ice_packed', 1]],
    [[5,2], ['heavy_weighted_pressure_plate', '', 'Weighted Pressure Plate (Heavy)', true, '', 2]],
    [[6,0], ['oak_leaves', '', 'Leaves (Oak)', false, 'leaves', 0]],
    [[6,1], ['spruce_leaves', '', 'Leaves (Spruce)', false, 'leaves', 1]],
    [[6,2], ['birch_leaves', '', 'Leaves (Birch)', false, 'leaves', 2]],
    [[6,3], ['jungle_leaves', '', 'Leaves (Jungle)', false, 'leaves', 3]],
    [[6,4], ['acacia_leaves', '', 'Leaves (Acacia)', false, 'leaves', 4]],
    [[6,5], ['dark_oak_leaves', '', 'Leaves (Dark Oak)', false, 'leaves', 5]],
    [[7,0], ['clay', '', 'Clay', false, '', 0]],
    [[8,0], ['jungle_log', "'axis':'y'", 'Jungle Log (vertical)', false, 'log_jungle_top', 0]],
    [[8,1], ['jungle_planks', '', 'Jungle Planks', false, 'planks_jungle', 1]],
    [[8,2], ['jungle_slab', '', 'Jungle Slab', false, 'slabs_jungle', 2]],
    [[8,4], ['coarse_dirt', '', 'Coarse Dirt', false, '', 4]],
    [[8,6], ['granite', '', 'Granite', false, 'stone_granite', 6]],
    [[9,2], ['stone_slab', '', 'Stone Slab', false, '', 2]],
    [[9,3], ['cobblestone_slab', '', 'Cobblestone Slab', false, 'cobblestone_slab', 3]],
    [[9,4], ['andesite', '', 'Andesite', false, 'stone_andesite', 4]],
    [[9,6], ['acacia_log', "'axis':'x'", 'Acacia Log (horizontal)', false, 'log_acacia', 6]],
    [[10,0], ['water', '', 'Water (Unsupported!)', true, 'water_bucket', 0]],
    [[11,0], ['oak_log', "'axis':'y'", 'Oak Log (vertical)', false, 'log_oak_top', 0]],
    [[11,1], ['oak_planks', '', 'Oak Planks', false, 'planks_oak', 1]],
    [[11,2], ['oak_slab', '', 'Oak Slab', false, 'slabs_oak', 2]],
    [[12,0], ['birch_log', "'axis':'x'", 'Birch Log (horizontal)', false, 'log_birch', 0]],
    [[12,1], ['diorite', '', 'Diorite', false, 'stone_diorite', 1]],
    [[12,3], ['quartz_slab', '', 'Quartz Slab', false, 'quartz_slab', 3]],
    [[12,4], ['sea_lantern', '', 'Sea Lantern', false, '', 4]],
    [[13,0], ['white_wool', '', 'White Wool', false, 'wool_colored_white', 0]],
    [[13,1], ['white_carpet', '', 'White Carpet', true, 'carpet_colored_white', 1]],
    [[13,2], ['white_stained_glass', '', 'White Stained Glass', true, 'glass_white', 2]],
    [[13,3], ['white_concrete', '', 'White Concrete', false, 'concrete_white', 3]],
    [[13,4], ['white_concrete_powder', '', 'White Concrete Powder', true, 'concrete_powder_white', 4]],
    [[13,6], ['snow_block', '', 'Snow Block', false, 'snow', 6]],
    [[13,7], ['snow', '', 'Snow Layer', true, 'snow_layer', 7]],
    [[14,0], ['orange_wool', '', 'Orange Wool', false, 'wool_colored_orange', 0]],
    [[14,1], ['orange_carpet', '', 'Orange Carpet', true, 'carpet_colored_orange', 1]],
    [[14,2], ['orange_stained_glass', '', 'Orange Stained Glass', true, 'glass_orange', 2]],
    [[14,3], ['orange_concrete', '', 'Orange Concrete', false, 'concrete_orange', 3]],
    [[14,4], ['orange_concrete_powder', '', 'Orange Concrete Powder', true, 'concrete_powder_orange', 4]],
    [[14,6], ['acacia_log', "'axis':'y'", 'Acacia Log (vertical)', false, 'log_acacia_top', 6]],
    [[14,7], ['acacia_planks', '', 'Acacia Planks', false, 'planks_acacia', 7]],
    [[14,8], ['acacia_slab', '', 'Acacia Slab', false, 'slabs_acacia', 8]],
    [[14,9], ['red_sand', '', 'Red Sand', true, 'red_sand', 9]],
    [[14,10], ['red_sandstone', '', 'Red Sandstone', false, 'red_sandstone_normal', 10]],
    [[14,11], ['terracotta', '', 'Terracotta', false, 'hardened_clay', 11]],
    [[15,0], ['magenta_wool', '', 'Magenta Wool', false, 'wool_colored_magenta', 0]],
    [[15,1], ['magenta_carpet', '', 'Magenta Carpet', true, 'carpet_colored_magenta', 1]],
    [[15,2], ['magenta_stained_glass', '', 'Magenta Stained Glass', true, 'glass_magenta', 2]],
    [[15,3], ['magenta_concrete', '', 'Magenta Concrete', false, 'concrete_magenta', 3]],
    [[15,4], ['magenta_concrete_powder', '', 'Magenta Concrete Powder', true, 'concrete_powder_magenta', 4]],
    [[15,7], ['purpur_slab', '', 'Purpur Slab', false, '', 7]],
    [[16,0], ['light_blue_wool', '', 'Light Blue Wool', false, 'wool_colored_light_blue', 0]],
    [[16,1], ['light_blue_carpet', '', 'Light Blue Carpet', true, 'carpet_colored_light_blue', 1]],
    [[16,2], ['light_blue_stained_glass', '', 'Light Blue Stained Glass', true, 'glass_light_blue', 2]],
    [[16,3], ['light_blue_concrete', '', 'Light Blue Concrete', false, 'concrete_light_blue', 3]],
    [[16,4], ['light_blue_concrete_powder', '', 'Light Blue Concrete Powder', true, 'concrete_powder_light_blue', 4]],
    [[16,5], ['light_blue_glazed_terracotta', '', 'Light Blue Glazed Terracotta', false, 'glazed_terracotta_light_blue', 5]],
    [[17,0], ['yellow_wool', '', 'Yellow Wool', false, 'wool_colored_yellow', 0]],
    [[17,1], ['yellow_carpet', '', 'Yellow Carpet', true, 'carpet_colored_yellow', 1]],
    [[17,2], ['yellow_stained_glass', '', 'Yellow Stained Glass', true, 'glass_yellow', 2]],
    [[17,3], ['yellow_concrete', '', 'Yellow Concrete', false, 'concrete_yellow', 3]],
    [[17,4], ['yellow_concrete_powder', '', 'Yellow Concrete Powder', true, 'concrete_powder_yellow', 4]],
    [[17,7], ['sponge', '', 'Sponge (any)', false, '', 7]],
    [[18,0], ['lime_wool', '', 'Lime Wool', false, 'wool_colored_lime', 0]],
    [[18,1], ['lime_carpet', '', 'Lime Carpet', true, 'carpet_colored_lime', 1]],
    [[18,2], ['lime_stained_glass', '', 'Lime Stained Glass', true, 'glass_lime', 2]],
    [[18,3], ['lime_concrete', '', 'Lime Concrete', false, 'concrete_lime', 3]],
    [[18,4], ['lime_concrete_powder', '', 'Lime Concrete Powder', true, 'concrete_powder_lime', 4]],
    [[18,6], ['melon', '', 'Melon', false, 'melon_side', 6]],
    [[19,0], ['pink_wool', '', 'Pink Wool', false, 'wool_colored_pink', 0]],
    [[19,1], ['pink_carpet', '', 'Pink Carpet', true, 'carpet_colored_pink', 1]],
    [[19,2], ['pink_stained_glass', '', 'Pink Stained Glass', true, 'glass_pink', 2]],
    [[19,3], ['pink_concrete', '', 'Pink Concrete', false, 'concrete_pink', 3]],
    [[19,4], ['pink_concrete_powder', '', 'Pink Concrete Powder', true, 'concrete_powder_pink', 4]],
    [[19,5], ['pink_glazed_terracotta', '', 'Pink Glazed Terracotta', false, 'glazed_terracotta_pink', 5]],
    [[20,0], ['gray_wool', '', 'Gray Wool', false, 'wool_colored_gray', 0]],
    [[20,1], ['gray_carpet', '', 'Gray Carpet', true, 'carpet_colored_gray', 1]],
    [[20,2], ['gray_stained_glass', '', 'Gray Stained Glass', true, 'glass_gray', 2]],
    [[20,3], ['gray_concrete', '', 'Gray Concrete', false, 'concrete_gray', 3]],
    [[20,4], ['gray_concrete_powder', '', 'Gray Concrete Powder', true, 'concrete_powder_gray', 4]],
    [[20,5], ['gray_glazed_terracotta', '', 'Gray Glazed Terracotta', false, 'glazed_terracotta_gray', 5]],
    [[21,0], ['light_gray_wool', '', 'Light Gray Wool', false, 'wool_colored_silver', 0]],
    [[21,1], ['light_gray_carpet', '', 'Light Gray Carpet', true, 'carpet_colored_silver', 1]],
    [[21,2], ['light_gray_stained_glass', '', 'Light Gray Stained Glass', true, 'glass_silver', 2]],
    [[21,3], ['light_gray_concrete', '', 'Light Gray Concrete', false, 'concrete_silver', 3]],
    [[21,4], ['light_gray_concrete_powder', '', 'Light Gray Concrete Powder', true, 'concrete_powder_silver', 4]],
    [[21,5], ['light_gray_glazed_terracotta', '', 'Light Gray Glazed Terracotta', false, 'glazed_terracotta_silver', 5]],
    [[22,0], ['cyan_wool', '', 'Cyan Wool', false, 'wool_colored_cyan', 0]],
    [[22,1], ['cyan_carpet', '', 'Cyan Carpet', true, 'carpet_colored_cyan', 1]],
    [[22,2], ['cyan_stained_glass', '', 'Cyan Stained Glass', true, 'glass_cyan', 2]],
    [[22,3], ['cyan_concrete', '', 'Cyan Concrete', false, 'concrete_cyan', 3]],
    [[22,4], ['cyan_concrete_powder', '', 'Cyan Concrete Powder', true, 'concrete_powder_cyan', 4]],
    [[22,6], ['prismarine', '', 'Prismarine', false, '', 6]],
    [[23,0], ['purple_wool', '', 'Purple Wool', false, 'wool_colored_purple', 0]],
    [[23,1], ['purple_carpet', '', 'Purple Carpet', true, 'carpet_colored_purple', 1]],
    [[23,2], ['purple_stained_glass', '', 'Purple Stained Glass', true, 'glass_purple', 2]],
    [[23,3], ['purple_concrete', '', 'Purple Concrete', false, 'concrete_purple', 3]],
    [[23,4], ['purple_concrete_powder', '', 'Purple Concrete Powder', true, 'concrete_powder_purple', 4]],
    [[23,6], ['mycelium', '', 'Mycelium', false, 'mycelium_side', 6]],
    [[24,0], ['blue_wool', '', 'Blue Wool', false, 'wool_colored_blue', 0]],
    [[24,1], ['blue_carpet', '', 'Blue Carpet', true, 'carpet_colored_blue', 1]],
    [[24,2], ['blue_stained_glass', '', 'Blue Stained Glass', true, 'glass_blue', 2]],
    [[24,3], ['blue_concrete', '', 'Blue Concrete', false, 'concrete_blue', 3]],
    [[24,4], ['blue_concrete_powder', '', 'Blue Concrete Powder', true, 'concrete_powder_blue', 4]],
    [[24,5], ['blue_glazed_terracotta', '', 'Blue Glazed Terracotta', false, 'glazed_terracotta_blue', 5]],
    [[25,0], ['brown_wool', '', 'Brown Wool', false, 'wool_colored_brown', 0]],
    [[25,1], ['brown_carpet', '', 'Brown Carpet', true, 'carpet_colored_brown', 1]],
    [[25,2], ['brown_stained_glass', '', 'Brown Stained Glass', true, 'glass_brown', 2]],
    [[25,3], ['brown_concrete', '', 'Brown Concrete', false, 'concrete_brown', 3]],
    [[25,4], ['brown_concrete_powder', '', 'Brown Concrete Powder', true, 'concrete_powder_brown', 4]],
    [[25,6], ['dark_oak_log', "'axis':'y'", 'Dark Oak Log (any direction)', false, 'log_big_oak', 6]],
    [[25,7], ['dark_oak_planks', '', 'Dark Oak Planks', false, 'planks_big_oak', 7]],
    [[25,8], ['dark_oak_slab', '', 'Dark Oak Slab', false, 'slabs_big_oak', 8]],
    [[25,9], ['spruce_log', "'axis':'x'", 'Spruce Log (horizontal)', false, 'log_spruce', 9]],
    [[25,10], ['soul_sand', '', 'Soul Sand', false, '', 10]],
    [[26,0], ['green_wool', '', 'Green Wool', false, 'wool_colored_green', 0]],
    [[26,1], ['green_carpet', '', 'Green Carpet', true, 'carpet_colored_green', 1]],
    [[26,2], ['green_stained_glass', '', 'Green Stained Glass', true, 'glass_green', 2]],
    [[26,3], ['green_concrete', '', 'Green Concrete', false, 'concrete_green', 3]],
    [[26,4], ['green_concrete_powder', '', 'Green Concrete Powder', true, 'concrete_powder_green', 4]],
    [[26,5], ['green_glazed_terracotta', '', 'Green Glazed Terracotta', false, 'glazed_terracotta_green', 5]],
    [[27,0], ['red_wool', '', 'Red Wool', false, 'wool_colored_red', 0]],
    [[27,1], ['red_carpet', '', 'Red Carpet', true, 'carpet_colored_red', 1]],
    [[27,2], ['red_stained_glass', '', 'Red Stained Glass', true, 'glass_red', 2]],
    [[27,3], ['red_concrete', '', 'Red Concrete', false, 'concrete_red', 3]],
    [[27,4], ['red_concrete_powder', '', 'Red Concrete Powder', true, 'concrete_powder_red', 4]],
    [[27,6], ['bricks', '', 'Bricks', false, 'brick', 6]],
    [[27,7], ['nether_wart_block', '', 'Nether Wart Block', false, '', 7]],
    [[28,0], ['black_wool', '', 'Black Wool', false, 'wool_colored_black', 0]],
    [[28,1], ['black_carpet', '', 'Black Carpet', true, 'carpet_colored_black', 1]],
    [[28,2], ['black_stained_glass', '', 'Black Stained Glass', true, 'glass_black', 2]],
    [[28,3], ['black_concrete', '', 'Black Concrete', false, 'concrete_black', 3]],
    [[28,4], ['black_concrete_powder', '', 'Black Concrete Powder', true, 'concrete_powder_black', 4]],
    [[28,7], ['obsidian', '', 'Obsidian', false, '', 7]],
    [[29,1], ['light_weighted_pressure_plate', '', 'Weighted Pressure Plate (Light)', true, '', 1]],
    [[30,1], ['prismarine_bricks', '', 'Prismarine Bricks', false, 'prismarine_bricks', 1]],
    [[30,2], ['dark_prismarine', '', 'Dark Prismarine', false, 'prismarine_dark', 2]],
    [[30,3], ['beacon', '', 'Beacon', true, '', 3]],
    [[31,0], ['lapis_block', '', 'Lapis Lazuli Block', false, '', 0]],
    [[32,0], ['emerald_block', '', 'Block of Emerald', false, '', 0]],
    [[33,0], ['spruce_log', "'axis':'y'", 'Spruce Log (vertical)', false, 'log_spruce_top', 0]],
    [[33,1], ['spruce_planks', '', 'Spruce Planks', false, 'planks_spruce', 1]],
    [[33,2], ['spruce_slab', '', 'Spruce Slab', false, 'slabs_spruce', 2]],
    [[33,3], ['oak_log', "'axis':'x'", 'Oak Log (horizontal)', false, 'log_oak', 3]],
    [[33,4], ['jungle_log', "'axis':'x'", 'Jungle Log (horizontal)', false, 'log_jungle', 4]],
    [[33,5], ['podzol', '', 'Podzol', false, 'dirt_podzol_side', 5]],
    [[34,1], ['nether_bricks', '', 'Nether Brick', false, 'nether_brick', 1]],
    [[34,2], ['nether_brick_slab', '', 'Nether Brick Slab', false, '', 2]],
    [[34,3], ['magma_block', '', 'Magma Block', false, 'magma', 3]],
    [[35,0], ['white_terracotta', '', 'White Terracotta', false, 'hardened_clay_stained_white', 0]],
    [[36,0], ['orange_terracotta', '', 'Orange Terracotta', false, 'hardened_clay_stained_orange', 0]],
    [[37,0], ['magenta_terracotta', '', 'Magenta Terracotta', false, 'hardened_clay_stained_magenta', 0]],
    [[38,0], ['light_blue_terracotta', '', 'Light Blue Terracotta', false, 'hardened_clay_stained_light_blue', 0]],
    [[39,0], ['yellow_terracotta', '', 'Yellow Terracotta', false, 'hardened_clay_stained_yellow', 0]],
    [[40,0], ['lime_terracotta', '', 'Lime Terracotta', false, 'hardened_clay_stained_lime', 0]],
    [[41,0], ['pink_terracotta', '', 'Pink Terracotta', false, 'hardened_clay_stained_pink', 0]],
    [[42,0], ['gray_terracotta', '', 'Gray Terracotta', false, 'hardened_clay_stained_gray', 0]],
    [[43,0], ['light_gray_terracotta', '', 'Light Gray Terracotta', false, 'hardened_clay_stained_silver', 0]],
    [[44,0], ['cyan_terracotta', '', 'Cyan Terracotta', false, 'hardened_clay_stained_cyan', 0]],
    [[45,0], ['purple_terracotta', '', 'Purple Terracotta', false, 'hardened_clay_stained_purple', 0]],
    [[46,0], ['blue_terracotta', '', 'Blue Terracotta', false, 'hardened_clay_stained_blue', 0]],
    [[47,0], ['brown_terracotta', '', 'Brown Terracotta', false, 'hardened_clay_stained_brown', 0]],
    [[48,0], ['green_terracotta', '', 'Green Terracotta', false, 'hardened_clay_stained_green', 0]],
    [[49,0], ['red_terracotta', '', 'Red Terracotta', false, 'hardened_clay_stained_red', 0]],
    [[50,0], ['black_terracotta', '', 'Black Terracotta', false, 'hardened_clay_stained_black', 0]],
  ]
}
window.mapdatmappings = [1,2,3,4,5,6,7,9,10,11,12,13,14,8,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51];